# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.dailycppinterview.com/
title: Daily C++ Interview
email: sandor@dailycppinterview.com
author: Sandor Dargo
tagline: Get a C++ question every day to prepare for your interviews
description: > # "Write an awesome description for your new site here. 
  Daily C++ Interview is a service that helps you to prepare for your 
  upcoming Cpp interviews. You are going to receive a question
  every day. If you are a Pro member, you will also get the answers.
copyright: 'Copyright &copy; 2020 DailyCppInterview'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
plugins: [jekyll-seo-tag]

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #


